update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,10 +3,10 @@ name: Test-Build
 on:
   push:
     branches:
-      [ main ]
+      [main]
   pull_request:
     branches:
-      [ main ]
+      [main]
 
 jobs:
   test:
@@ -27,15 +27,22 @@ jobs:
       - name: Run tests
         run: npm run test
 
+      - name: Verify report exists
+        run: |
+          if [ ! -f "newman/newman-run-report.html" ]; then
+            echo "HTML report not found!" && exit 1
+          fi
+
       - name: Upload HTML report
         uses: actions/upload-artifact@v4
         with:
           name: newman-report
-          path: newman/*.html
-        
+          path: newman/newman-run-report.html
+
       - name: Deploy report
         uses: JamesIves/github-pages-deploy-action@4.1.3
         if: always()
         with:
           branch: gh-pages
-          folder: newman
+          folder: ${{ github.workspace }}/newman
+          clean: false
