update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,10 +3,10 @@ name: Test-Build
 on:
   push:
     branches:
-      - main
+      [ main ]
   pull_request:
     branches:
-      - main
+      [ main ]
 
 jobs:
   test:
@@ -33,9 +33,16 @@ jobs:
           name: newman-report
           path: newman/*.html
 
+      - name: Verify report exists
+        run: |
+            if [ ! -f "newman/newman-run-report.html" ]; then
+              echo "HTML report not found!" && exit 1
+            fi
+        
       - name: Deploy report
         uses: JamesIves/github-pages-deploy-action@4.1.3
         if: always()
         with:
           branch: gh-pages
-          folder: ./
+          folder: newman
+          clean: false
